; -----------------------------------------------------------------------
; Template source file generated by piklab
    #include <p16f628a.inc>

; -----------------------------------------------------------------------
; Configuration bits:
    __CONFIG _WDT_OFF & _PWRTE_ON & _XT_OSC & _MCLRE_ON & _BODEN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF

; -----------------------------------------------------------------------
; Variables declaration
	udata
lc1	res		1
lc2	res		1
index	res		1
bits	res		1

; -----------------------------------------------------------------------
; reset vector
STARTUP CODE		0x000
	nop                    		; needed for ICD2 debugging
	movlw		high start	; load upper byte of 'start' label
	movwf		PCLATH		; initialize PCLATH
	goto		start		; go to start of main code

PROG	code

dawdle
	clrf		lc1
	clrf		lc2
dawdle1
	decfsz		lc1,f
	goto		dawdle1
	decfsz		lc2,f
	goto		dawdle1
	return
	
start
	banksel		TRISB
	errorlevel	-302
	movlw		H'f1'
	movwf		TRISB
	banksel		PORTB
	errorlevel	+302

outerloop

	call		dawdle
	call		dawdle
	clrf		index
innerloop
	movf		index,W
	banksel		EEADR
	errorlevel	-302
	movwf		EEADR
	nop
	bsf		EECON1,RD
	nop
	movf		EEDATA,W
	banksel		bits
	errorlevel	+302
	movwf		bits
	swapf		bits,W
	movwf		PORTB
	call		dawdle
	movf		bits,W
	movwf		PORTB
	call		dawdle
	incf		index,F
	movf		index,W
	sublw		H'4f'
	btfss		STATUS,Z
	goto		innerloop
	goto		outerloop


DEEPROM	code

	data	0x06,0x0a,0x04,0x0a,0x8e,0xa2,0xac,0xec	; 0x7
	data	0x48,0x20,0x6a,0x2a,0xc8,0x82,0xc4,0x46	; 0xf
	data	0x80,0x8e,0xae,0x20,0x2c,0x28,0x24,0x6e	; 0x17
	data	0x62,0x4e,0xee,0xae,0xae,0x02,0x0c,0x4e	; 0x1f
	data	0x40,0x0a,0x6a,0xe8,0xe2,0xa2,0xc6,0xc6	; 0x27
	data	0xee,0xe8,0x28,0x60,0x6c,0x6e,0xaa,0x84	; 0x2f
	data	0x82,0x8e,0xaa,0x2c,0x6c,0x48,0xee,0xe6	; 0x37
	data	0x04,0x8a,0x8e,0x04,0x0e,0x46,0x6e,0xec	; 0x3f
	data	0xe4,0xe4,0x64,0xee,0xee,0x4c,0x4e,0x6e	; 0x47
	data	0xec,0xee,0xee,0xcc,0xce,0xce,0xee,0xee	; 0x4f

	END
